apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
  labels:
    app: tech-challenge
spec:
  selector:
    app: tech-challenge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
