apiVersion: apps/v1
kind: Deployment
metadata:
  name: tofood-deployment
  labels:
    app: tofood
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tofood
  template:
    metadata:
      labels:
        app: tofood
    spec:
      containers:
      - name: tofood-container
        image: tofood/backend:latest  # Atualizado para usar a nova imagem do tofood
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
          - name: NODE_ENV
            value: "production"
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
