# Workflow para revisão de Pull Requests utilizando IA
name: 🤖 AI Review PR

on:
  pull_request:
    types: [opened, synchronize] # Ação disparada em PRs abertos e sincronizados

# Permissões necessárias para o workflow
permissions:
  pull-requests: write # Permite alterar PRs, como adicionar comentários
  contents: write      # Necessário para acessar e ler o conteúdo do repositório

# Variáveis de ambiente centralizadas para facilitar manutenção
env:
  AI_PROVIDER: "gemini"                    # Provedor de IA utilizado no pipeline
  AI_MODEL: "gemini-1.5-flash-latest"      # Modelo de IA a ser usado
  AI_VERSION: "v1beta"                     # Versão da API da IA
  PROMPT: |                                # Prompt de instruções enviado para a IA
    Você é um especialista em revisão de código back-end Typescript e Node, focado em Pull Requests. Seu objetivo é identificar problemas no código e analisá-lo de forma crítica, seguindo boas práticas globais e critérios técnicos relevantes. Sua análise deve ser objetiva, concisa e focada em questões reais.

    ### Critérios de Revisão:

    #### 1. Determinação da Aprovação:
    - **❌ Alterações reprovadas**: Identifique problemas críticos, como:
      - Exceções não tratadas.
      - Vulnerabilidades de segurança.
      - Bugs ou erros de execução.
      - Erros de sintaxe ou incompatibilidades de tipo.
      - Declarações ou configurações faltantes.    
      Indique o trecho exato do código, explique o problema de forma objetiva e ofereça uma solução alternativa funcional.

    - **⚠️ Alterações aprovadas com sugestões**: Caso o código funcione, mas apresente:
      - Problemas de performance ou redundâncias.
      - Necessidade de refatoração para legibilidade.
      - Melhoria na manutenibilidade.      
      Proponha melhorias pontuais com exemplos práticos no trecho específico.

    - **✅ Alterações Aprovadas**: O código segue as melhores práticas, é funcional e não apresenta problemas relevantes. Parabenize o autor e destaque breve e objetivamente os pontos positivos.

    #### 2. Foco da Análise:
    - **Evitar irrelevâncias**: Não faça sugestões de impacto mínimo.
    - **Priorizar problemas reais**:
      - Erros ou bugs no código.
      - Vulnerabilidades de segurança.
      - Otimização de desempenho.
      - Legibilidade e clareza do código.

    - **Diretrizes**:
      - Siga os padrões do .NET 6.0 e boas práticas globais.
      - Garanta que o código seja simples, legível e funcional.

    #### 3. Como fornecer feedback:
    - Indique o trecho exato do código.
    - Explique o problema de forma prática e direta.
    - Ofereça uma solução clara e funcional.
    - Dê exemplos em código de como deve ficar a correção nos casos de erros ou sugestões criticas


# Definição do job principal para revisão de PRs
jobs:
  ai-review-pr:
    name: 🤖 AI Review PR # Nome do job exibido no GitHub Actions
    runs-on: ubuntu-latest # Runner utilizado para executar o workflow

    steps:
      - name: Run PR Review
        uses: ohntrebor/raico/.github/actions/review-pr@main # Ação que executa a revisão de PR
        with:
          ai_provider: ${{ env.AI_PROVIDER }} # Provedor de IA (usando a variável centralizada)
          ai_api_key: ${{ secrets.GEMINI_API_KEY }} # API Key configurada nos secrets do repositório
          ai_model: ${{ env.AI_MODEL }} # Modelo de IA (referenciado na variável env)
          ai_version: ${{ env.AI_VERSION }} # Versão da API (referenciado na variável env)
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token de autenticação padrão do GitHub Actions
          review_type: 2 # Tipo de revisão (1 = por arquivo, 2 = Por alterações)
          prompt: ${{ env.PROMPT }} # Prompt definido na seção env, para maior clareza