name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Log in to Docker Hub para construir e publicar imagem
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construindo a imagem Docker, passando as variáveis de ambiente necessárias
      - name: Build Docker Image
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }} # Opcional, mas mantendo para flexibilidade
        run: |
          docker build \
          --build-arg DB_USER=${DB_USER} \
          --build-arg DB_PASSWORD=${DB_PASSWORD} \
          --build-arg DB_HOST=${DB_HOST} \
          --build-arg DB_NAME=${DB_NAME} \
          --build-arg DB_PORT=${DB_PORT} \
          -t leonardo10sp/tech-challenge:latest .

      # Empurrando a imagem Docker para o Docker Hub
      - name: Push Docker Image
        run: docker push leonardo10sp/tech-challenge:latest

      # Configuração do kubectl e aplicação dos manifests no Kubernetes
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "v1.20.0"

      - name: Configure kubeconfig
        run: aws eks update-kubeconfig --name tofood-eks-cluster

      # Aplicando os manifests do Kubernetes
      - name: Apply Kubernetes Manifests
        run: kubectl apply -f ./k8s
