name: Update Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}

    steps:
      # Passo 1: Fazer o checkout do repositório (atualizado para v4)
      - name: Fazer checkout do repositório
        uses: actions/checkout@v4

      # Passo 2: Configurar Docker Buildx (atualizado para v3)
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Passo 3: Verificar se as variáveis de ambiente estão configuradas
      - name: Verificar variáveis de ambiente
        run: |
          if [ -z "${DOCKER_USERNAME}" ]; then
            echo "Erro: A variável DOCKER_USERNAME não está definida."
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Erro: A variável DOCKER_PASSWORD não está definida."
            exit 1
          fi

      # Passo 4: Logar no Docker Hub (atualizado para v3)
      - name: Logar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 5: Construir a imagem Docker
      - name: Construir Imagem Docker
        run: |
          docker build -t leonardo10sp/tech-challenge:latest .

      # Passo 6: Enviar a imagem Docker para o Docker Hub
      - name: Enviar Imagem Docker
        run: |
          docker push leonardo10sp/tech-challenge:latest

      # Passo 7: Opcionalmente, taguear e enviar com a SHA do commit específico
      - name: Taguear Imagem Docker com SHA do Commit
        run: |
          IMAGE_TAG="leonardo10sp/tech-challenge:${{ github.sha }}"
          docker tag leonardo10sp/tech-challenge:latest $IMAGE_TAG
          docker push $IMAGE_TAG
