# Caminho do Arquivo: .github/workflows/docker-image-update.yml

name: Atualizar Imagem Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do repositório (atualizado para v3)
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar o Docker Buildx (para suporte a imagens multi-plataforma, se necessário)
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Passo 3: Logar no Docker Hub (utilizando os segredos)
      - name: Logar no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 4: Construir a imagem Docker
      - name: Construir Imagem Docker
        run: |
          docker build -t leonardo10sp/tech-challenge:latest .

      # Passo 5: Enviar a imagem Docker para o Docker Hub
      - name: Enviar Imagem Docker
        run: |
          docker push leonardo10sp/tech-challenge:latest
          
      # Passo 6: Opcionalmente, taguear e enviar com a SHA do commit específico
      - name: Taguear Imagem Docker com SHA do Commit
        run: |
          IMAGE_TAG="leonardo10sp/tech-challenge:${{ github.sha }}"
          docker tag leonardo10sp/tech-challenge:latest $IMAGE_TAG
          docker push $IMAGE_TAG
