# File Path: .github/workflows/test.yml

name: Run User Tests

# Disparar o workflow quando ocorrer um push ou pull request na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Step 4: Executar os testes do UserTest.ts
      - name: Run UserTest
        run: npx jest src/tests/UserTest.ts
