name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: "docker.io"
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: "tofood/backend"  # Nome da sua imagem no Docker Hub

    steps:
      - name: 🎨 Fazer checkout do repositório
        uses: actions/checkout@v4

      - name: 🐋 Login no Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin

      - name: 🛠️ Build da imagem Docker
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:latest .

      - name: 🏷️ Tag da imagem
        run: |
          docker tag $DOCKER_REGISTRY/$IMAGE_NAME:latest $DOCKER_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: 📤 Push da imagem Docker
        run: |
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: ✅ Logout do Docker
        run: |
          docker logout $DOCKER_REGISTRY
